/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.BibliotecaControlador;
import ec.edu.ups.controlador.LibroControlador;
import ec.edu.ups.controlador.PrestamoControlador;
import ec.edu.ups.controlador.UsuarioControlador;
import ec.edu.ups.dao.BibliotecaDao;
import ec.edu.ups.dao.LibroDao;
import ec.edu.ups.dao.PrestamoDao;
import ec.edu.ups.dao.UsuarioDao;
import ec.edu.ups.idao.IBibliotecaDao;
import ec.edu.ups.idao.ILibroDao;
import ec.edu.ups.idao.IPrestamoDao;
import ec.edu.ups.idao.IUsuarioDao;
import ec.edu.ups.vista.Biblioteca.VentanaBuscarBiblioteca;
import ec.edu.ups.vista.Biblioteca.VentanaCrearBiblioteca;
import ec.edu.ups.vista.Biblioteca.VentanaEditarBiblioteca;
import ec.edu.ups.vista.Biblioteca.VentanaEliminarBiblioteca;
import ec.edu.ups.vista.Biblioteca.VentanaListarBiblioteca;
import ec.edu.ups.vista.Libro.VentanaBuscarLibro;
import ec.edu.ups.vista.Libro.VentanaCrearLibro;
import ec.edu.ups.vista.Libro.VentanaDevolver;
import ec.edu.ups.vista.Libro.VentanaEditarLibro;
import ec.edu.ups.vista.Libro.VentanaEliminarLibro;
import ec.edu.ups.vista.Libro.VentanaListarLibro;
import ec.edu.ups.vista.Libro.VentanaPrestar;
import ec.edu.ups.vista.Prestamo.VentanaBuscarPrestamo;
import ec.edu.ups.vista.Prestamo.VentanaCrearPrestamo;
import ec.edu.ups.vista.Prestamo.VentanaEditarPrestamo;
import ec.edu.ups.vista.Prestamo.VentanaEliminarPrestamo;
import ec.edu.ups.vista.Prestamo.VentanaListarPrestamo;
import ec.edu.ups.vista.usuario.VentanaBuscarUsuario;
import ec.edu.ups.vista.usuario.VentanaCrearUsuario;
import ec.edu.ups.vista.usuario.VentanaEditarUsuario;
import ec.edu.ups.vista.usuario.VentanaEliminarUsuario;
import ec.edu.ups.vista.usuario.VentanaListarUsuario;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author fernan
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private VentanaCrearBiblioteca ventanaCrearBiblioteca;
    private VentanaBuscarBiblioteca ventanaBuscarBiblioteca;
    private VentanaEditarBiblioteca ventanaEditarBiblioteca;
    private VentanaEliminarBiblioteca ventanaEliminarBiblioteca;
    private VentanaListarBiblioteca ventanaListarBibliotecas;

    private IBibliotecaDao bibliotecaDao;                   //se intanciona en el constructor
    private BibliotecaControlador bibliotecaControlador;

    private VentanaCrearLibro ventanaCrearLibro;
    private VentanaBuscarLibro ventanaBuscarLibro;
    private VentanaEditarLibro ventanaEditarLibro;
    private VentanaEliminarLibro ventanaEliminarLibro;
    private VentanaListarLibro ventanaListarLibro;
    private VentanaPrestar ventanaPrestar;
    private VentanaDevolver ventanaDevolver;
    
    private ILibroDao libroDao;                   //se intanciona en el constructor
    private LibroControlador libroControlador;

    private VentanaCrearUsuario ventanaCrearUsuario;
    private VentanaBuscarUsuario ventanaBuscarUsuario;
    private VentanaEditarUsuario ventanaEditarUsuario;
    private VentanaEliminarUsuario ventanaEliminarUsuario;
    private VentanaListarUsuario ventanaListarUsuario;

    private IUsuarioDao usuarioDao;
    private UsuarioControlador usuarioControlador;

    private VentanaCrearPrestamo ventanaCrearPrestamo;
    private VentanaBuscarPrestamo ventanaBuscarPrestamo;
    private VentanaEditarPrestamo ventanaEditarPrestamo;
    private VentanaEliminarPrestamo ventanaEliminarPrestamo;
    private VentanaListarPrestamo ventanaListarPrestamo;

    private IPrestamoDao prestamoDao;
    private PrestamoControlador prestamoControlador;
    private Locale locale;

    public VentanaPrincipal() {
        initComponents();
        //siempre se intancia luego de initComponents para evitar problemas

        bibliotecaDao = new BibliotecaDao();
        bibliotecaControlador = new BibliotecaControlador(bibliotecaDao);
        libroDao = new LibroDao();
        libroControlador = new LibroControlador(libroDao);
        usuarioDao = new UsuarioDao();
        usuarioControlador = new UsuarioControlador(usuarioDao);
        prestamoDao = new PrestamoDao();
        prestamoControlador = new PrestamoControlador(prestamoDao);

        locale = new Locale("es", "EC");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        MenuBiblioteca = new javax.swing.JMenu();
        crearBiblioteca = new javax.swing.JMenuItem();
        buscarBiblioteca = new javax.swing.JCheckBoxMenuItem();
        editarBiblioteca = new javax.swing.JMenuItem();
        eliminarBiblioteca = new javax.swing.JMenuItem();
        listarBiblioteca = new javax.swing.JMenuItem();
        MenuLibro = new javax.swing.JMenu();
        crearLibro = new javax.swing.JMenuItem();
        buscarLibro = new javax.swing.JCheckBoxMenuItem();
        editarLibro = new javax.swing.JMenuItem();
        eliminarLibro = new javax.swing.JMenuItem();
        listarLibro = new javax.swing.JMenuItem();
        Prestar = new javax.swing.JMenuItem();
        Devolver = new javax.swing.JMenuItem();
        MenuUsuario = new javax.swing.JMenu();
        crearUsuario = new javax.swing.JMenuItem();
        buscarUsuario = new javax.swing.JCheckBoxMenuItem();
        editarUsuario = new javax.swing.JMenuItem();
        eliminarUsuario = new javax.swing.JMenuItem();
        listarUsuarios = new javax.swing.JMenuItem();
        MenuPrestamo = new javax.swing.JMenu();
        crearPrestamo = new javax.swing.JMenuItem();
        buscarPrestamo = new javax.swing.JCheckBoxMenuItem();
        editarPrestamo = new javax.swing.JMenuItem();
        eliminarPrestamo = new javax.swing.JMenuItem();
        listarPrestamo = new javax.swing.JMenuItem();
        MenuOpciones = new javax.swing.JMenu();
        salirPrograma = new javax.swing.JCheckBoxMenuItem();
        MenuIngles = new javax.swing.JMenuItem();
        menuIngles = new javax.swing.JMenuItem();
        menuFrances = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setAutoscrolls(true);
        desktopPane.setDoubleBuffered(true);

        MenuBiblioteca.setMnemonic('f');
        MenuBiblioteca.setText("Biblioteca");
        MenuBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBibliotecaActionPerformed(evt);
            }
        });

        crearBiblioteca.setMnemonic('o');
        crearBiblioteca.setText("Crear");
        crearBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearBibliotecaActionPerformed(evt);
            }
        });
        MenuBiblioteca.add(crearBiblioteca);

        buscarBiblioteca.setSelected(true);
        buscarBiblioteca.setText("Buscar");
        buscarBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBibliotecaActionPerformed(evt);
            }
        });
        MenuBiblioteca.add(buscarBiblioteca);

        editarBiblioteca.setMnemonic('s');
        editarBiblioteca.setText("Editar");
        editarBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBibliotecaActionPerformed(evt);
            }
        });
        MenuBiblioteca.add(editarBiblioteca);

        eliminarBiblioteca.setMnemonic('a');
        eliminarBiblioteca.setText("Eliminar");
        eliminarBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBibliotecaActionPerformed(evt);
            }
        });
        MenuBiblioteca.add(eliminarBiblioteca);

        listarBiblioteca.setMnemonic('x');
        listarBiblioteca.setText("Listar");
        listarBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarBibliotecaActionPerformed(evt);
            }
        });
        MenuBiblioteca.add(listarBiblioteca);

        menuBar.add(MenuBiblioteca);

        MenuLibro.setMnemonic('e');
        MenuLibro.setText("Libro");

        crearLibro.setMnemonic('o');
        crearLibro.setText("Crear");
        crearLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearLibroActionPerformed(evt);
            }
        });
        MenuLibro.add(crearLibro);

        buscarLibro.setSelected(true);
        buscarLibro.setText("Buscar");
        buscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarLibroActionPerformed(evt);
            }
        });
        MenuLibro.add(buscarLibro);

        editarLibro.setMnemonic('s');
        editarLibro.setText("Editar");
        editarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarLibroActionPerformed(evt);
            }
        });
        MenuLibro.add(editarLibro);

        eliminarLibro.setMnemonic('a');
        eliminarLibro.setText("Eliminar");
        eliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarLibroActionPerformed(evt);
            }
        });
        MenuLibro.add(eliminarLibro);

        listarLibro.setMnemonic('x');
        listarLibro.setText("Listar");
        listarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarLibroActionPerformed(evt);
            }
        });
        MenuLibro.add(listarLibro);

        Prestar.setMnemonic('o');
        Prestar.setText("Prestar");
        Prestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrestarActionPerformed(evt);
            }
        });
        MenuLibro.add(Prestar);

        Devolver.setMnemonic('o');
        Devolver.setText("Devolver");
        Devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevolverActionPerformed(evt);
            }
        });
        MenuLibro.add(Devolver);

        menuBar.add(MenuLibro);

        MenuUsuario.setMnemonic('h');
        MenuUsuario.setText("Usuario");

        crearUsuario.setMnemonic('o');
        crearUsuario.setText("Crear");
        crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearUsuarioActionPerformed(evt);
            }
        });
        MenuUsuario.add(crearUsuario);

        buscarUsuario.setSelected(true);
        buscarUsuario.setText("Buscar");
        buscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUsuarioActionPerformed(evt);
            }
        });
        MenuUsuario.add(buscarUsuario);

        editarUsuario.setMnemonic('s');
        editarUsuario.setText("Editar");
        editarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarUsuarioActionPerformed(evt);
            }
        });
        MenuUsuario.add(editarUsuario);

        eliminarUsuario.setMnemonic('a');
        eliminarUsuario.setText("Eliminar");
        eliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarUsuarioActionPerformed(evt);
            }
        });
        MenuUsuario.add(eliminarUsuario);

        listarUsuarios.setMnemonic('x');
        listarUsuarios.setText("Listar");
        listarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarUsuariosActionPerformed(evt);
            }
        });
        MenuUsuario.add(listarUsuarios);

        menuBar.add(MenuUsuario);

        MenuPrestamo.setText("Prestamo");

        crearPrestamo.setMnemonic('o');
        crearPrestamo.setText("Crear");
        crearPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPrestamoActionPerformed(evt);
            }
        });
        MenuPrestamo.add(crearPrestamo);

        buscarPrestamo.setSelected(true);
        buscarPrestamo.setText("Buscar");
        buscarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPrestamoActionPerformed(evt);
            }
        });
        MenuPrestamo.add(buscarPrestamo);

        editarPrestamo.setMnemonic('s');
        editarPrestamo.setText("Editar");
        editarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPrestamoActionPerformed(evt);
            }
        });
        MenuPrestamo.add(editarPrestamo);

        eliminarPrestamo.setMnemonic('a');
        eliminarPrestamo.setText("Eliminar");
        eliminarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPrestamoActionPerformed(evt);
            }
        });
        MenuPrestamo.add(eliminarPrestamo);

        listarPrestamo.setMnemonic('x');
        listarPrestamo.setText("Listar");
        listarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPrestamoActionPerformed(evt);
            }
        });
        MenuPrestamo.add(listarPrestamo);

        menuBar.add(MenuPrestamo);

        MenuOpciones.setText("Opciones");

        salirPrograma.setSelected(true);
        salirPrograma.setText("Salir");
        salirPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirProgramaActionPerformed(evt);
            }
        });
        MenuOpciones.add(salirPrograma);

        MenuIngles.setText("Ingles");
        MenuIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInglesActionPerformed(evt);
            }
        });
        MenuOpciones.add(MenuIngles);

        menuIngles.setText("Español");
        menuIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInglesActionPerformed(evt);
            }
        });
        MenuOpciones.add(menuIngles);

        menuFrances.setText("Fránces");
        menuFrances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFrancesActionPerformed(evt);
            }
        });
        MenuOpciones.add(menuFrances);

        menuBar.add(MenuOpciones);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1099, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarBibliotecaActionPerformed
        if (ventanaListarBibliotecas == null) {
            ventanaListarBibliotecas = new VentanaListarBiblioteca(bibliotecaControlador);
            ventanaListarBibliotecas.cambiarIdioma(locale);
        }

        if (!ventanaListarBibliotecas.isVisible()) {
            ventanaListarBibliotecas.setVisible(true);

            desktopPane.add(ventanaListarBibliotecas);
        }
    }//GEN-LAST:event_listarBibliotecaActionPerformed

    private void eliminarBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBibliotecaActionPerformed

        if (ventanaEliminarBiblioteca == null) {
            ventanaEliminarBiblioteca = new VentanaEliminarBiblioteca(bibliotecaControlador);
            ventanaEliminarBiblioteca.cambiarIdioma(locale);
        }

        if (!ventanaEliminarBiblioteca.isVisible()) {

            ventanaEliminarBiblioteca.setVisible(true);
            desktopPane.add(ventanaEliminarBiblioteca);
        }
    }//GEN-LAST:event_eliminarBibliotecaActionPerformed

    private void crearBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearBibliotecaActionPerformed
        // TODO add your handling code here:

        if (ventanaCrearBiblioteca == null) {
            ventanaCrearBiblioteca = new VentanaCrearBiblioteca(bibliotecaControlador);
            ventanaCrearBiblioteca.cambiarIdioma(locale);
        }

        if (!ventanaCrearBiblioteca.isVisible()) {

            ventanaCrearBiblioteca.setVisible(true);
            desktopPane.add(ventanaCrearBiblioteca);
        }
    }//GEN-LAST:event_crearBibliotecaActionPerformed

    private void MenuBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBibliotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuBibliotecaActionPerformed

    private void buscarBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBibliotecaActionPerformed
        // TODO add your handling code here:

        if (ventanaBuscarBiblioteca == null) {
            ventanaBuscarBiblioteca = new VentanaBuscarBiblioteca(bibliotecaControlador);
            ventanaBuscarBiblioteca.cambiarIdioma(locale);

        }

        if (!ventanaBuscarBiblioteca.isVisible()) {

            ventanaBuscarBiblioteca.setVisible(true);
            desktopPane.add(ventanaBuscarBiblioteca);
        }
    }//GEN-LAST:event_buscarBibliotecaActionPerformed

    private void editarBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBibliotecaActionPerformed
        if (ventanaEditarBiblioteca == null) {
            ventanaEditarBiblioteca = new VentanaEditarBiblioteca(bibliotecaControlador);
            ventanaEditarBiblioteca.cambiarIdioma(locale);

        }

        if (!ventanaEditarBiblioteca.isVisible()) {

            ventanaEditarBiblioteca.setVisible(true);
            desktopPane.add(ventanaEditarBiblioteca);
        }

    }//GEN-LAST:event_editarBibliotecaActionPerformed

    private void crearLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearLibroActionPerformed
        if (ventanaCrearLibro == null) {
            ventanaCrearLibro = new VentanaCrearLibro(libroControlador);
            ventanaCrearLibro.cambiarIdioma(locale);

        }

        if (!ventanaCrearLibro.isVisible()) {

            ventanaCrearLibro.setVisible(true);
            desktopPane.add(ventanaCrearLibro);
        }
    }//GEN-LAST:event_crearLibroActionPerformed

    private void buscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarLibroActionPerformed

        if (ventanaBuscarLibro == null) {
            ventanaBuscarLibro = new VentanaBuscarLibro(libroControlador);
            ventanaBuscarLibro.cambiarIdioma(locale);

        }

        if (!ventanaBuscarLibro.isVisible()) {

            ventanaBuscarLibro.setVisible(true);
            desktopPane.add(ventanaBuscarLibro);
        }

    }//GEN-LAST:event_buscarLibroActionPerformed

    private void editarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarLibroActionPerformed
        if (ventanaEditarLibro == null) {
            ventanaEditarLibro = new VentanaEditarLibro(libroControlador);
            ventanaEditarLibro.cambiarIdioma(locale);

        }

        if (!ventanaEditarLibro.isVisible()) {

            ventanaEditarLibro.setVisible(true);
            desktopPane.add(ventanaEditarLibro);
        }
    }//GEN-LAST:event_editarLibroActionPerformed

    private void eliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarLibroActionPerformed
        if (ventanaEliminarLibro == null) {
            ventanaEliminarLibro = new VentanaEliminarLibro(libroControlador);
            ventanaEliminarLibro.cambiarIdioma(locale);

        }

        if (!ventanaEliminarLibro.isVisible()) {

            ventanaEliminarLibro.setVisible(true);
            desktopPane.add(ventanaEliminarLibro);
        }
    }//GEN-LAST:event_eliminarLibroActionPerformed

    private void listarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarLibroActionPerformed
        if (ventanaListarLibro == null) {
            ventanaListarLibro = new VentanaListarLibro(libroControlador);
            ventanaListarLibro.cambiarIdioma(locale);

        }

        if (!ventanaListarLibro.isVisible()) {
            ventanaListarLibro.setVisible(true);
            ventanaListarLibro.cargarDatos();
            desktopPane.add(ventanaListarLibro);
        }

    }//GEN-LAST:event_listarLibroActionPerformed

    private void crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUsuarioActionPerformed
        if (ventanaCrearUsuario == null) {
            ventanaCrearUsuario = new VentanaCrearUsuario(usuarioControlador);
            ventanaCrearUsuario.cambiarIdioma(locale);

        }

        if (!ventanaCrearUsuario.isVisible()) {

            ventanaCrearUsuario.setVisible(true);
            desktopPane.add(ventanaCrearUsuario);
        }

    }//GEN-LAST:event_crearUsuarioActionPerformed

    private void buscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUsuarioActionPerformed
        if (ventanaBuscarUsuario == null) {
            ventanaBuscarUsuario = new VentanaBuscarUsuario(usuarioControlador);
            ventanaBuscarUsuario.cambiarIdioma(locale);

        }

        if (!ventanaBuscarUsuario.isVisible()) {

            ventanaBuscarUsuario.setVisible(true);
            desktopPane.add(ventanaBuscarUsuario);
        }

    }//GEN-LAST:event_buscarUsuarioActionPerformed

    private void editarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarUsuarioActionPerformed
        if (ventanaEditarUsuario == null) {
            ventanaEditarUsuario = new VentanaEditarUsuario(usuarioControlador);
            ventanaEditarUsuario.cambiarIdioma(locale);

        }

        if (!ventanaEditarUsuario.isVisible()) {

            ventanaEditarUsuario.setVisible(true);
            desktopPane.add(ventanaEditarUsuario);
        }
    }//GEN-LAST:event_editarUsuarioActionPerformed

    private void eliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarUsuarioActionPerformed
        if (ventanaEliminarUsuario == null) {
            ventanaEliminarUsuario = new VentanaEliminarUsuario(usuarioControlador);
            ventanaEliminarUsuario.cambiarIdioma(locale);

        }

        if (!ventanaEliminarUsuario.isVisible()) {

            ventanaEliminarUsuario.setVisible(true);
            desktopPane.add(ventanaEliminarUsuario);
        }
    }//GEN-LAST:event_eliminarUsuarioActionPerformed

    private void listarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarUsuariosActionPerformed
        if (ventanaListarUsuario == null) {
            ventanaListarUsuario = new VentanaListarUsuario(usuarioControlador);
            ventanaListarUsuario.cambiarIdioma(locale);

        }

        if (!ventanaListarUsuario.isVisible()) {
            ventanaListarUsuario.setVisible(true);
            ventanaListarUsuario.cargarDatos();
            desktopPane.add(ventanaListarUsuario);
        }
    }//GEN-LAST:event_listarUsuariosActionPerformed

    private void salirProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirProgramaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirProgramaActionPerformed

    private void crearPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPrestamoActionPerformed

        if (ventanaCrearPrestamo == null) {
            ventanaCrearPrestamo = new VentanaCrearPrestamo(prestamoControlador, libroControlador, usuarioControlador);
            ventanaCrearPrestamo.cambiarIdioma(locale);

        }

        if (!ventanaCrearPrestamo.isVisible()) {

            ventanaCrearPrestamo.setVisible(true);
            desktopPane.add(ventanaCrearPrestamo);
        }
    }//GEN-LAST:event_crearPrestamoActionPerformed

    private void buscarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPrestamoActionPerformed

        if (ventanaBuscarPrestamo == null) {
            ventanaBuscarPrestamo = new VentanaBuscarPrestamo(prestamoControlador);
            ventanaBuscarPrestamo.cambiarIdioma(locale);

        }

        if (!ventanaBuscarPrestamo.isVisible()) {

            ventanaBuscarPrestamo.setVisible(true);
            desktopPane.add(ventanaBuscarPrestamo);
        }
    }//GEN-LAST:event_buscarPrestamoActionPerformed

    private void editarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPrestamoActionPerformed

        if (ventanaEditarPrestamo == null) {
            ventanaEditarPrestamo = new VentanaEditarPrestamo(prestamoControlador,libroControlador,usuarioControlador);
            ventanaEditarPrestamo.cambiarIdioma(locale);

        }

        if (!ventanaEditarPrestamo.isVisible()) {

            ventanaEditarPrestamo.setVisible(true);
            desktopPane.add(ventanaEditarPrestamo);
        }

    }//GEN-LAST:event_editarPrestamoActionPerformed

    private void eliminarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPrestamoActionPerformed
        if (ventanaEliminarPrestamo == null) {
            ventanaEliminarPrestamo = new VentanaEliminarPrestamo(prestamoControlador);
            ventanaEliminarPrestamo.cambiarIdioma(locale);

        }

        if (!ventanaEliminarPrestamo.isVisible()) {

            ventanaEliminarPrestamo.setVisible(true);
            desktopPane.add(ventanaEliminarPrestamo);
        }
    }//GEN-LAST:event_eliminarPrestamoActionPerformed

    private void listarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarPrestamoActionPerformed
        if (ventanaListarPrestamo == null) {
            ventanaListarPrestamo = new VentanaListarPrestamo(prestamoControlador);
            ventanaListarPrestamo.cambiarIdioma(locale);

        }

        if (!ventanaListarPrestamo.isVisible()) {
            ventanaListarPrestamo.setVisible(true);
            ventanaListarPrestamo.cargarDatos();
            desktopPane.add(ventanaListarPrestamo);
        }
    }//GEN-LAST:event_listarPrestamoActionPerformed

    private void MenuInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInglesActionPerformed
        locale = new Locale("en", "US");
        cambiarIdioma();
    }//GEN-LAST:event_MenuInglesActionPerformed
    private void menuInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInglesActionPerformed
        locale = new Locale("es", "EC");
        cambiarIdioma();
    }//GEN-LAST:event_menuInglesActionPerformed
    private void menuFrancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFrancesActionPerformed
        locale = new Locale("fr", "FR");
        cambiarIdioma();
    }//GEN-LAST:event_menuFrancesActionPerformed

    private void PrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrestarActionPerformed
         if (ventanaPrestar == null) {
            ventanaPrestar = new VentanaPrestar(usuarioControlador,libroControlador,prestamoControlador);
            ventanaPrestar.cambiarIdioma(locale);

        }

        if (!ventanaPrestar.isVisible()) {
            ventanaPrestar.setVisible(true);
            ventanaPrestar.cargarDatos();
            desktopPane.add(ventanaPrestar);
        }
    }//GEN-LAST:event_PrestarActionPerformed

    private void DevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevolverActionPerformed
        if (ventanaDevolver == null) {
            ventanaDevolver = new VentanaDevolver(usuarioControlador,libroControlador,prestamoControlador);
            ventanaDevolver.cambiarIdioma(locale);

        }

        if (!ventanaDevolver.isVisible()) {
            ventanaDevolver.setVisible(true);
            ventanaDevolver.cargarDatos();
            desktopPane.add(ventanaDevolver);
        }
    }//GEN-LAST:event_DevolverActionPerformed
    private void cambiarIdioma() {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        MenuBiblioteca.setText(mensajes.getString("MenuBiblioteca"));
        MenuLibro.setText(mensajes.getString("MenuLibro"));
        crearBiblioteca.setText(mensajes.getString("crearBiblioteca"));
        buscarBiblioteca.setText(mensajes.getString("buscarBiblioteca"));
        editarBiblioteca.setText(mensajes.getString("editarBiblioteca"));
        eliminarBiblioteca.setText(mensajes.getString("eliminarBiblioteca"));
        listarBiblioteca.setText(mensajes.getString("listarBiblioteca"));
        MenuUsuario.setText(mensajes.getString("MenuUsuario"));
        MenuPrestamo.setText(mensajes.getString("MenuPrestamo"));
        MenuOpciones.setText(mensajes.getString("MenuOpciones"));
        buscarLibro.setText(mensajes.getString("buscarLibro"));
        crearLibro.setText(mensajes.getString("crearLibro"));
        editarLibro.setText(mensajes.getString("editarLibro"));
        eliminarLibro.setText(mensajes.getString("eliminarLibro"));
        listarLibro.setText(mensajes.getString("listarLibro"));
        buscarUsuario.setText(mensajes.getString("buscarUsuario"));
        buscarPrestamo.setText(mensajes.getString("buscarPrestamo"));
        crearUsuario.setText(mensajes.getString("crearUsuario"));
        crearPrestamo.setText(mensajes.getString("crearPrestamo"));
        editarUsuario.setText(mensajes.getString("editarUsuario"));
        editarPrestamo.setText(mensajes.getString("editarPrestamo"));
        eliminarUsuario.setText(mensajes.getString("eliminarUsuario"));
        listarUsuarios.setText(mensajes.getString("listarUsuarios"));
        listarPrestamo.setText(mensajes.getString("listarPrestamo"));
        MenuIngles.setText(mensajes.getString("MenuIngles"));
        menuIngles.setText(mensajes.getString("menuIngles"));
        menuFrances.setText(mensajes.getString("menuFrances"));
        salirPrograma.setText(mensajes.getString("salirPrograma"));
        eliminarPrestamo.setText(mensajes.getString("eliminarPrestamo"));
        if (ventanaCrearBiblioteca != null) {
            ventanaCrearBiblioteca.cambiarIdioma(locale);
        }
        if (ventanaBuscarBiblioteca != null) {
            ventanaBuscarBiblioteca.cambiarIdioma(locale);
        }
        if (ventanaEditarBiblioteca != null) {
            ventanaEditarBiblioteca.cambiarIdioma(locale);
        }
        if (ventanaEliminarBiblioteca != null) {
            ventanaEliminarBiblioteca.cambiarIdioma(locale);
        }
        if (ventanaListarBibliotecas != null) {
            ventanaListarBibliotecas.cambiarIdioma(locale);
        }
        if (ventanaCrearLibro != null) {
            ventanaCrearLibro.cambiarIdioma(locale);
        }
        if (ventanaBuscarLibro != null) {
            ventanaBuscarLibro.cambiarIdioma(locale);
        }
        if (ventanaEditarLibro != null) {
            ventanaEditarLibro.cambiarIdioma(locale);
        }
        if (ventanaEliminarLibro != null) {
            ventanaEliminarLibro.cambiarIdioma(locale);
        }
        if (ventanaListarLibro != null) {
            ventanaListarLibro.cambiarIdioma(locale);
        }
        if (ventanaBuscarUsuario != null) {
            ventanaBuscarUsuario.cambiarIdioma(locale);
        }
        if (ventanaCrearUsuario != null) {
            ventanaCrearUsuario.cambiarIdioma(locale);
        }
        if (ventanaEditarUsuario != null) {
            ventanaEditarUsuario.cambiarIdioma(locale);
        }
        if (ventanaEliminarUsuario != null) {
            ventanaEliminarUsuario.cambiarIdioma(locale);
        }
        if (ventanaListarUsuario != null) {
            ventanaListarUsuario.cambiarIdioma(locale);
        }
        if (ventanaBuscarPrestamo != null) {
            ventanaBuscarPrestamo.cambiarIdioma(locale);
        }
        if (ventanaCrearPrestamo != null) {
            ventanaCrearPrestamo.cambiarIdioma(locale);
        }
        if (ventanaEditarPrestamo != null) {
            ventanaEditarPrestamo.cambiarIdioma(locale);
        }
        if (ventanaEliminarPrestamo != null) {
            ventanaEliminarPrestamo.cambiarIdioma(locale);
        }
        if (ventanaListarPrestamo != null) {
            ventanaListarPrestamo.cambiarIdioma(locale);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Devolver;
    private javax.swing.JMenu MenuBiblioteca;
    private javax.swing.JMenuItem MenuIngles;
    private javax.swing.JMenu MenuLibro;
    private javax.swing.JMenu MenuOpciones;
    private javax.swing.JMenu MenuPrestamo;
    private javax.swing.JMenu MenuUsuario;
    private javax.swing.JMenuItem Prestar;
    private javax.swing.JCheckBoxMenuItem buscarBiblioteca;
    private javax.swing.JCheckBoxMenuItem buscarLibro;
    private javax.swing.JCheckBoxMenuItem buscarPrestamo;
    private javax.swing.JCheckBoxMenuItem buscarUsuario;
    private javax.swing.JMenuItem crearBiblioteca;
    private javax.swing.JMenuItem crearLibro;
    private javax.swing.JMenuItem crearPrestamo;
    private javax.swing.JMenuItem crearUsuario;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem editarBiblioteca;
    private javax.swing.JMenuItem editarLibro;
    private javax.swing.JMenuItem editarPrestamo;
    private javax.swing.JMenuItem editarUsuario;
    private javax.swing.JMenuItem eliminarBiblioteca;
    private javax.swing.JMenuItem eliminarLibro;
    private javax.swing.JMenuItem eliminarPrestamo;
    private javax.swing.JMenuItem eliminarUsuario;
    private javax.swing.JMenuItem listarBiblioteca;
    private javax.swing.JMenuItem listarLibro;
    private javax.swing.JMenuItem listarPrestamo;
    private javax.swing.JMenuItem listarUsuarios;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuFrances;
    private javax.swing.JMenuItem menuIngles;
    private javax.swing.JCheckBoxMenuItem salirPrograma;
    // End of variables declaration//GEN-END:variables

}
